### ISSUE TITLE
Map not loading properly on latest version.

### ISSUE THREAD

**Issue by welbertwpg** [rcelyte/MappingExtensions#1]
Hello,

I've tried to play [this map](https://beatsaver.com/maps/b04c) in the latest version of the mod, but the map didn't load correctly, instead of creating a street scenario it's creating some walls that make the map unplayable.

A screenshot of the issue:
![Error](https://user-images.githubusercontent.com/13783059/187028491-1c8186ca-24c4-43b8-884e-66c39e6d3db7.png)

How it should be:
![image](https://user-images.githubusercontent.com/13783059/187028527-80fd6410-3a74-4824-9ea8-bc5d673cb86c.png)

I haven't tried other maps that use this mod, but could be affecting other maps as well.

It used to work in the [previous version of the mod](https://github.com/rxzz0/MappingExtensions/releases/tag/0.20.2) on Beat Saber 1.17.1

Thanks for all your work and effort! :)

**Comment by rcelyte** [comment]
Thanks for the report! Can you confirm whether or not v0.21.2 fixed this issue?

**Comment by welbertwpg** [comment]
Yes, v0.21.2 has fixed the issue. Thank you very much!
