### ISSUE TITLE
Chains and Arcs

### ISSUE THREAD

**Issue by Manleyne** [rcelyte/MappingExtensions#3]
Some levels, like [this one](https://beatsaver.com/maps/230dc), have a few chain and arc notes incorrectly positioned only when ME is enabled.

[Example](https://streamable.com/houfod)

**Comment by rcelyte** [comment]
Looks like my prior testing wasn't thorough enough o_0
Should be fixed in v0.21.4.

**Comment by Manleyne** [comment]
you unbroked it alright 👍
