### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by finnhelp** [rcelyte/MappingExtensions#4]
some maps i play crash as soon as i click on them when its enabled

**Comment by rcelyte** [comment]
What other mods do you have installed?
Are all your mods updated to their latest released versions?
Which maps specifically are crashing?

**Comment by finnhelp** [comment]
well this is the only mod right now but maps that don't require any mods are crashing the game

**Comment by rcelyte** [comment]
So 1.24.0; only core mods and MappingExtensions? Do *all* maps crash or just specific ones?

**Comment by finnhelp** [comment]
all maps that dont need like chroma, noodle, mapping. ect

**Comment by rcelyte** [comment]
Alright. I need a list of every mod you have installed (core mods included) and its version, as listed in BMBF.

**Comment by rcelyte** [comment]
Fixed in v0.21.5
