### ISSUE TITLE
Level Replay Issues

### ISSUE THREAD

**Issue by Manleyne** [rcelyte/MappingExtensions#5]
Playing the same level more than once in one session with ME installed will cause [this](https://streamable.com/kekdu3) to happen to the notes, at least to an extent, on any map.

It can be most noticeable on [this map](https://beatsaver.com/maps/1a669). You should be able to just play through the first few seconds of the level, and then restart it to get it to happen.

I am unable to reproduce this issue without ME installed.

**Comment by rcelyte** [comment]
I am unable to reproduce this issue in testing. Does it still occur if you only have ME + core mods?

**Comment by rcelyte** [comment]
Closing as outdated. Please open a new issue if you're able to reproduce this on Beat Saber 1.35.0.
