### ISSUE TITLE
update to 1.35 beat saber

### ISSUE THREAD

**Issue by FilimonEnc** [rcelyte/MappingExtensions#7]
I know I've already created an Issue, but please keep this one and close it as soon as it's finished, I'd like to be notified that it's done.
I’ll also ask, off topic, are you developing noodle Extension, and will mapping include noodle/chroma?

**Comment by rcelyte** [comment]
> are you developing Noodle Extensions?

The only mod I maintain is MappingExtensions (and barely that considering my hardware situation is less than optimal). Progress is currently blocked on an issue in the modloader hampering my ability to test anything, so my hands are tied until the others can get that fixed.

**Comment by FilimonEnc** [comment]
Thanks for the answer. We'll be looking forward to progress!

**Comment by phazei** [comment]
Just a heads up, I noticed the https://github.com/Kylemc1413/MappingExtensions/ version has just recently been updated for 1.35.  I wasn't sure if that's necessary to help port it to the quest.

https://github.com/Kylemc1413/MappingExtensions/commit/46bf5673ec312372d04203025ad1fd08041368f8

**Comment by rcelyte** [comment]
Those changes are already implemented.

**Comment by rcelyte** [comment]
So uh funny story apparently the code I wrote two months ago worked perfectly fine and nobody told me. It's released now, sorry about the wait 😅.

**Comment by rcelyte** [comment]
It seems I was misinformed (as usual 🙄). Walls are still completely broken.

**Comment by phazei** [comment]
What a roller coaster 😆

I'm curious, is this a port of the desktop one, or is it only done in parallel?  Is implementation entirely different?

**Comment by rcelyte** [comment]
Half and half. A large number of the functions modified by PC MappingExtensions can't be hooked on Quest due to how the game is compiled, so different (read: worse) approaches needed to be found i.e. restoring note positions retroactively rather than bypassing the code that breaks them to begin with.

**Comment by rcelyte** [comment]
Well it's been a day since release now and nobody has complained about anything being broken so I *think* I got it right this time :+1:
