### ISSUE TITLE
broken wall size on 1.35

### ISSUE THREAD

**Issue by gfififid** [rcelyte/MappingExtensions#8]
Map: https://beatsaver.com/maps/67a8
there is even unplayeble part of the song becouse of it
examples of broken parts in videos:

https://github.com/rcelyte/MappingExtensions/assets/62612037/ac200cf8-997c-4300-abfa-9f34b0b2cc60

https://github.com/rcelyte/MappingExtensions/assets/62612037/c3d8525c-c6e1-4d86-be00-b4b8b7543370

**Comment by FrozenAlex** [comment]
Confirmed the same behavior on 1.37.0

**Comment by rcelyte** [comment]
Please send log files. I can't figure anything out with just videos.

**Comment by rcelyte** [comment]
I've pulled the release in the meantime. It appears our testing wasn't thorough enough.

**Comment by rcelyte** [comment]
Fixed in v0.23.1
