### ISSUE TITLE
Port to 1.37

### ISSUE THREAD

**Issue by Windows98SE-dev** [rcelyte/MappingExtensions#9]
Could you please port the mod to 1.37 ?

Thanks

**Comment by rcelyte** [comment]
I can't do testing since I don't have a Quest on hand, but here's the untested pre-release if you'd like to try for yourself: https://github.com/rcelyte/MappingExtensions/releases/tag/0.24.0

**Comment by Windows98SE-dev** [comment]
Thank you very much, I'll tell you if it works or not

**Comment by Windows98SE-dev** [comment]
I'll tell you when I can becuase right now MBF is freaking out with it, it throws me this error : "Failed to import file: Error: `Failed to parse manifest Caused by: QMOD specified schema version 1.2.0 which was newer than the maximum supported version 1.1.0. Is MBF out of date, or did the mod developer make a mistake?`" So I asked them if MBF was outdated or not

**Comment by HasAks38** [comment]
Just imported the unreleased port to my quest 2 through Mods Before Friday, ill update in a moment

**Comment by HasAks38** [comment]
amazing!! it works perfectly! ill provide a rather laggy vid in a bit. it works for me! :D

**Comment by rcelyte** [comment]
So... video?

**Comment by VGer2072** [comment]
It works for me. Thx ! (Quest3+Questpatcher(scotland2)+Manually added via MBF)

**Comment by rcelyte** [comment]
released.
